Deskto version
MMGGYY66/my-portfolio-website pull request #5
Opened 2022-12-08 20:23 UTC by MMGGYY66

Converting mobile version to desktop.

2022-12-08 21:14 UTC, tufoinnkuo10 requested changes
Hi @MMGGYY66 

There are some issues that you still need to work on to go to the next project but you are almost there!

To Highlight
✅ You used the correct Github flow
✅ Descriptive pull request message
✅ linter error checks validated
✅ Documented your work professionally
✅ Media query well used
✅ Desktop design well implemented

Required Changes ♻️
Check the comments under the review
![tufoin](https://media.giphy.com/media/TZNLFZh5TeNRJKQXzm/giphy.gif)
Optional suggestions
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)

2022-12-08 21:14 UTC, tufoinnkuo10 commented on index.html
> +    <!-- start header section -->
- [ ] great work. Please ensure that as from screen size above 375, the mobile version should be responsive but well organized like the Figma. Please fix the text covering the background image at that screen size.
![Screenshot (651)_LI](https://user-images.githubusercontent.com/65298048/206565006-73345372-9f13-45d0-b9e3-613d599006f8.jpg)

2022-12-08 21:14 UTC, tufoinnkuo10 commented on index.html
> +        <div class="main-image"></div>
- [ ] please kindly add the multipost story image in both your desktop and mobile version, so your design matches the original Figma design. nice work

yours 
![Screenshot (652)_LI](https://user-images.githubusercontent.com/65298048/206565807-add346c5-13a2-4284-9d2d-c86a7da6c471.jpg)
figma
![Screenshot (653)](https://user-images.githubusercontent.com/65298048/206565931-3e0c9662-2a3c-431e-a68d-a259ea960fbd.png)

2022-12-08 21:14 UTC, tufoinnkuo10 commented on index.html
> +            <li>Ruby</li>
- [ ] please kindly align the language frameworks and skills like that of figma.
yours
![Screenshot (654)_LI](https://user-images.githubusercontent.com/65298048/206567759-b7b94188-6d77-4440-884e-20030171d219.jpg)
figma design
![Screenshot (655)](https://user-images.githubusercontent.com/65298048/206567864-8e89e733-3a8f-4c50-9ceb-e4f3c09cae96.png)

2022-12-08 21:14 UTC, tufoinnkuo10 commented on index.html
> +          Your email should be written in lower case.
- [ ] the error message is showing in your desktop and mobile version without the user trying to submit the form. please fix that

2022-12-08 21:14 UTC, tufoinnkuo10 commented on index.html
> +        I'm always interested in hearing about new projects, so if you'd like
- [ ] kindly use the correct font color for desktop version of text... `#262626`

2022-12-09 14:00 UTC, franclobo requested changes
Hi @MMGGYY66, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights

- No linter errors ✔️ 
- Correct Github flow ✔️ 
- Descriptive PR ✔️ 
- Professional README file ✔️ 


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-09 14:00 UTC, franclobo commented on style.css
>  }
- [ ] As the last code reviewer said 👉🏽 Kindly align the language frameworks and skills like that of Figma. Please 🙏🏽 make sure that both desktop and mobile versions look similar to the Figma template.

| Figma template | Your design |
|---|---|
| ![image](https://user-images.githubusercontent.com/58642949/206717096-fa77ac27-e12a-4be1-9b9f-14231c2cb5b1.png) | ![image](https://user-images.githubusercontent.com/58642949/206718758-41dab930-3741-4037-96ed-31667bfa068d.png) |

2022-12-09 14:50 UTC, christianbiring1 approved these changes
Hi @MMGGYY66 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
# STATUS: APPROVED :tada: 
![nicee](https://user-images.githubusercontent.com/97100091/206728435-e66ed9fc-905a-45b9-8b15-379bf081d6d4.gif)

## Highlights
- [ ] All linters checks are green :heavy_check_mark: 
- [ ] Descriptive PR `title` and `summary` :+1: 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-09 14:52 UTC, merged